[package]
name = "mlir"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[build-dependencies]
bindgen = "0.64.0"
cmake = "0.1.49"
git2 = "0.16.1"
pkg-config = "0.3.26"
cxx-build = "1.0.91"

[dependencies]
cxx = "1.0.91"